name: Gradle build and publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      if: github.event_name != 'pull_request'
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build
      run: ./gradlew build

    - name: Upload JAR to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: ./output/asn-blacklist-*.jar
        generate_release_notes: true

    - name: Upload Velocity build to Modrinth
      uses: RubixDev/modrinth-upload@v1
      with:
        token: ${{ secrets.MODRINTH_TOKEN }}
        file_path: ./output/asn-blacklist-velocity.jar
        name: Release ${{ github.ref_name }}
        version: ${{ github.ref_name }}
        changelog: Release ${{ github.ref_name }}
        game_versions: 1.7.2,1.7.3,1.7.4,1.7.5,1.7.6,1.7.7,1.7.8,1.7.9,1.7.10,1.8,1.8.1,1.8.2,1.8.3,1.8.4,1.8.5,1.8.6,1.8.7,1.8.8,1.8.9,1.9,1.9.1,1.9.2,1.9.3,1.9.4,1.10,1.10.1,1.10.2,1.11,1.11.1,1.11.2,1.12,1.12.1,1.12.2,1.13,1.13.1,1.13.2,1.14,1.14.1,1.14.2,1.14.3,1.14.4,1.15,1.15.1,1.15.2,1.16,1.16.1,1.16.2,1.16.3,1.16.4,1.16.5,1.17,1.17.1,1.18,1.18.1,1.18.2,1.19,1.19.1,1.19.2,1.19.3,1.19.4,1.20,1.20.1,1.20.2,1.20.3,1.20.4,1.20.5,1.20.6,1.21,1.21.1,1.21.2,1.21.3,1.21.4,1.21.5,1.21.6,1.21.7,1.21.8
        release_type: release
        loaders: velocity
        featured: true
        project_id: 1wBP58Vx

    - name: Upload BungeeCord build to Modrinth
      uses: RubixDev/modrinth-upload@v1
      with:
        token: ${{ secrets.MODRINTH_TOKEN }}
        file_path: ./output/asn-blacklist-bungee.jar
        name: Release ${{ github.ref_name }}
        version: ${{ github.ref_name }}
        changelog: Release ${{ github.ref_name }}
        game_versions: 1.8,1.8.1,1.8.2,1.8.3,1.8.4,1.8.5,1.8.6,1.8.7,1.8.8,1.8.9,1.9,1.9.1,1.9.2,1.9.3,1.9.4,1.10,1.10.1,1.10.2,1.11,1.11.1,1.11.2,1.12,1.12.1,1.12.2,1.13,1.13.1,1.13.2,1.14,1.14.1,1.14.2,1.14.3,1.14.4,1.15,1.15.1,1.15.2,1.16,1.16.1,1.16.2,1.16.3,1.16.4,1.16.5,1.17,1.17.1,1.18,1.18.1,1.18.2,1.19,1.19.1,1.19.2,1.19.3,1.19.4,1.20,1.20.1,1.20.2,1.20.3,1.20.4,1.20.5,1.20.6,1.21,1.21.1,1.21.2,1.21.3,1.21.4,1.21.5,1.21.6,1.21.7,1.21.8
        release_type: release
        loaders: bungeecord
        featured: true
        project_id: 1wBP58Vx
